name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
            
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - run: |
          pnpm install
      - run: |
          pnpm run all
  test_tag_found: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: version
        with:
          token: ${{ github.token }}
          tag: false
          tag_prefix: test/v
          release_months: |
            July
            January
  test_no_tag: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ github.token }}
          tag: false
          tag_prefix: test-unknown/v
          release_months: |
            July
            January
